preprocess:
    steps:
        - add_temporal_features
        - add_statistical_features
        - drop_redundant_features
    statistical_features:
    - downX
    - downY
    - downPressure
    - intertap