steps:
- name: python:3.7
  id: tests
  entrypoint: bash
  env:
    - "PYTHONPATH=/python-backend/lib"
  args: [-c 'python-backend/scripts/run_tests.sh']
  waitFor: ['requirements']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'cd python-backend/src/main && gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy --version=test']
  waitFor: ['tests']

