steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'cd python-backend && gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy --version=test']
timeout: '1600s'